-- Creating tables for postgres
CREATE TABLE Highered_data (
     Year INT NOT NULL,
     UNITID INT NOT NULL,
	 FACTSTAT INT NOT NULL,
	 ARANK INT NOT NULL,
	 HRTOTLT INT NOT NULL,
	 HRTOTLM INT NOT NULL,
	 HRTOTLW INT NOT NULL,
	 INSTNM VARCHAR NOT NULL,
	 CITY VARCHAR NOT NULL,
	 STABBR VARCHAR NOT NULL,
	 ZIP INT NOT NULL,
	 CONTROL INT NOT NULL,
	 HLOFFER INT NOT NULL,
	 INSTSIZE INT NOT NULL,
	 LONGITUD INT NOT NULL,
	 LATITUDE INT NOT NULL,
     PRIMARY KEY (UNITID)
);


CREATE TABLE Appointment_type (
	 ARANK INT NOT NULL,
	 HRTOTLT INT NOT NULL,
     PRIMARY KEY (ARANK)
);

CREATE TABLE Institution_size (
     Year INT NOT NULL,
     UNITID INT NOT NULL,
	 HRTOTLT INT NOT NULL,
	 HRTOTLM INT NOT NULL,
	 HRTOTLW INT NOT NULL,
	 HLOFFER INT NOT NULL,
	 INSTSIZE INT NOT NULL,
     PRIMARY KEY (UNITID)
);

CREATE TABLE Gender (
     Year INT NOT NULL,
     UNITID INT NOT NULL,
	 HRTOTLT INT NOT NULL,
	 HRTOTLM INT NOT NULL,
	 HRTOTLW INT NOT NULL,
     PRIMARY KEY (UNITID)
);

CREATE TABLE Faculty_status (
	 FACSTAT INT NOT NULL,
	 HRTOTLT INT NOT NULL,
	 PRIMARY KEY (FACSTAT)
);

SELECT * FROM Highered_data
SELECT * FROM Appointment_type
SELECT * FROM Institution_size
SELECT * FROM Gender
SELECT * FROM Faculty_status